### ISSUE TITLE
AsyncAPi to MD - TypeError: message.messageId is not a function

### ISSUE THREAD

**Issue by abhikt48** [asyncapi/generator#1068]
#### Describe the bug
AsyncAPi generator is working fine on windows and alpine base images, however it is not working on on Ubantu system. We are getting `TypeError: message.messageId is not a function`. 

We have tried with many possiblities like convert with latest version, use same converter versions from working system, but nothing works. It will be highly appreciated, if anyone can suggest/guide/hint what could be issue? 

#### Error
```
TypeError: message.messageId is not a function
    at Message (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template/components/Message.js:29:22)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:26)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:49:10)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)

```
## Versions
Below versions are available on the Ubantu OS

```
node version: v20.8.0
npm version: 10.2.0
ag version: 1.13.1
```
We have also tested with latest async api version `1.14.1`, but we are having same issue.

#### Used command to conver
`ag test.asyncapi.yaml @asyncapi/markdown-template -o ./ -p outFilename=test-1.yaml.md --force-write --debug`

#### Complete Debug Logs
```
Unable to resolve template location at undefined. Package is not available locally. Error: Cannot find module '@asyncapi/markdown-template/package.json'
Require stack:
- /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/resolve-from/index.js:43:9)
    at module.exports (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/resolve-from/index.js:46:47)
    at utils.getTemplateDetails (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/lib/utils.js:207:30)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/lib/generator.js:379:26
    at new Promise (<anonymous>)
    at Generator.installTemplate (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/lib/generator.js:372:12)
    at Generator.generate (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/lib/generator.js:180:73)
    at Generator.generateFromFile (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/lib/generator.js:342:17)
    at async /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/cli.js:157:9 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/noop.js'
  ]
}
Template installation started because the template cannot be found on disk.
Template @asyncapi/markdown-template successfully installed in /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template.
Version of used template is 1.4.0.
File /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template/hooks couldn't be found. Error: ENOENT: no such file or directory, stat '/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template/hooks'
Something went wrong:
TypeError: message.messageId is not a function
    at Message (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template/components/Message.js:29:22)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:26)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:49:10)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:34:12)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:12)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at normalizeProps (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:12:22)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:31)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:12)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:49:10)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:34:12)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:12)
    at /var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:34:12)
    at createElement (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:12)
    at Object.render (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:74:16)
    at renderFile (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/template.ts:81:14)
    at Object.<anonymous> (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/src/renderer/template.ts:36:10)
    at step (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/lib/renderer/template.js:33:23)
    at Object.next (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/lib/renderer/template.js:14:53)
    at fulfilled (/var/vsts/xx-agent-xx-2/_tool/node/20.8.0/x64/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/generator-react-sdk/lib/renderer/template.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

#### Expected behavior
MD file should be generated.

**Comment by jonaslagoni** [comment]
Lets keep it all in https://github.com/asyncapi/markdown-template/issues/385 🙂
