### ISSUE TITLE
cannot get streetlights to work

### ISSUE THREAD

**Issue by madiot** [asyncapi/generator#131]
Hello,

i'm on debian
```$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

```
$ npm --version
6.11.3

$ node --version
v10.16.0
```

Tried to follow the [tutorial on streetlights](https://www.asyncapi.org/docs/tutorials/streetlights/)
Could you please help in finding what i could possibly have missed, or done wrong?

I'm new to npm dev, so i created a local package as below

```
$ cat package.json
{
  "name": "streetlights",
  "version": "1.0.0",
  "description": "streetlights AsyncAPI.org tutorial",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "asyncapi-generator": "^0.16.0",
    "asyncapi-node-codegen": "^1.3.2",
    "mqtt": "^3.0.0"
  }
}
```

having the asyncapi.yaml 
```
$ cat asyncapi.yaml
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  mosquitto:
    url: localhost:1884
    scheme: mqtt

channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      payload:
        type: object
        properties:
          id:
            type: integer
            minimum: 0
            description: Id of the streetlight.
          lumens:
            type: integer
            minimum: 0
            description: Light intensity measured in lumens.
          sentAt:
            type: string
            format: date-time
            description: Date and time when the message was sent.

```

whether i install packages locally installed or globally with the 'npm -g install' with
```
ag asyncapi.yaml nodejs -p server=mosquitto
```

i'm getting this error
```
$ ag asyncapi.yaml nodejs -p server=mosquitto
Something went wrong:
Error: Invalid AsyncAPI document
    at parse (/usr/lib/node_modules/asyncapi-generator/node_modules/asyncapi-parser/lib/parser.js:93:11)
[
    {
        "dataPath": ".servers['mosquitto']",
        "keyword": "additionalProperties",
        "message": "should NOT have additional properties",
        "params": {
            "additionalProperty": "scheme"
        },
        "schemaPath": "#/additionalProperties"
    },
    {
        "dataPath": ".servers['mosquitto']",
        "keyword": "required",
        "message": "should have required property 'protocol'",
        "params": {
            "missingProperty": "protocol"
        },
        "schemaPath": "#/required"
    },
    {
        "dataPath": ".channels['light/measured'].publish",
        "keyword": "additionalProperties",
        "message": "should NOT have additional properties",
        "params": {
            "additionalProperty": "payload"
        },
        "schemaPath": "#/additionalProperties"
    }
]
```

finally, i tried to generate the docs both in markdown and html, but this fails too :
```
ag -o docs asyncapi.yaml html
Something went wrong:
Error: Invalid AsyncAPI document
    at parse (/usr/lib/node_modules/asyncapi-generator/node_modules/asyncapi-parser/lib/parser.js:93:11)
[
    {
        "keyword":"additionalProperties",
        "dataPath":".servers['mosquitto']",
        "schemaPath":"#/additionalProperties",
        "params": {
                "additionalProperty":"scheme"
        },
        "message":"should NOT have additional properties"
    },
    {
        "keyword":"required",
        "dataPath":".servers['mosquitto']",
        "schemaPath":"#/required",
        "params":{
                "missingProperty":"protocol"
        },
        "message":"should have required property 'protocol'"
     }, 
     {
        "keyword":"additionalProperties",
        "dataPath":".channels['light/measured'].publish",
        "schemaPath":"#/additionalProperties",
        "params":{
                "additionalProperty":"payload"
        },
        "message":"should NOT have additional properties"
     }
]

```

tried also with the [streetlights.yml](https://github.com/asyncapi/generator/blob/master/test/docs/streetlights.yml) and ran successfully with with command 
```
$ ag streelights.yml nodejs -p server=production
Done! ✨
```

**Comment by fmvilas** [comment]
Oops. We mistakenly left the `scheme` property in the server object. Please, rename it to `protocol`. I'll also fix it now on the website. Thanks!

**Comment by fmvilas** [comment]
I fixed it on the website and confirmed it works. Thanks for reporting.
