### ISSUE TITLE
Template render error using byTags sidebarOrganization

### ISSUE THREAD

**Issue by rv0** [asyncapi/generator#141]
ag asyncapi.yaml html --param sidebarOrganization=byTags
```
Something went wrong:
Template render error: (unknown path)
  Template render error: (/usr/local/lib/node_modules/asyncapi-generator/templates/html/.partials/sidebar.html)
  Error: Unable to call `the return value of (the return value of (channel["subscribe"])["tags"])["0"]["name"]`, which is undefined or falsey
    at Object._prettifyError (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:24:11)
    at /usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:575:11
    at eval (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:12:11)
    at /usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:617:9
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:63:3)
    at Template.getExported (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:11:5)
    at createTemplate (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:315:9)
```

Any ideas what is going wrong?

**Comment by fmvilas** [comment]
I'm trying to reproduce the error but I can't. Do you mind sharing an example of an AsyncAPI document with me?

**Comment by rv0** [comment]
Found the problem. One channel did not have any tags defined.. Shouldn't crash like this though :s
 
Using version 0.22.1 btw

**Comment by fmvilas** [comment]
Agree it shouldn't crash. Thanks for reporting!

**Comment by jonaslagoni** [comment]
Hey @rv0 are you able to share your template and api definition? 

`... the return value of (channel["subscribe"])["tags"])["0"]["name"], which is undefined or falsey`

Normally this error would be because your template try to access the tags before checking if any are present, i.e try something like this ([based on stackoverflow](https://stackoverflow.com/a/39794612/6803886)):
```nunjucks
{%- if channel.subscribe().tags() | length %}
 ... do what ever here you need to do in regards to the tags
{%- endif %}
``` 
Where this is not a bug with the generator itself, since it should fail the parsing if it cannot do what you ask it to. If you have any questions just fire away :)

**Comment by rv0** [comment]
Thanks for the great work!
