### ISSUE TITLE
All files under template are rendered even if not template file

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#395]
#### Describe the bug
Sometimes you might want to include some binary files. In this case it can happen that the generator is unable to complete the generation in some cases.

With attached file the generator throws the following error:
```
+ @asyncapi/dotnet-nats-template@0.1.0
updated 1 package in 1.077s

3 packages are looking for funding
  run `npm fund` for details

Something went wrong:
Template render error: (path\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\dotnet-nats-template\template\packages\NATS.Client.0.10.1\.signature.p7s)
  Error: expected end of comment, got end of file
    at Object._prettifyError (path\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\lib.js:36:11)
    at Template.render (path\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:536:21)
    at Environment.renderString (path\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:378:17)
    at path\npm\node_modules\@asyncapi\generator\lib\generator.js:589:21
    at new Promise (<anonymous>)
    at Generator.renderString (path\npm\node_modules\@asyncapi\generator\lib\generator.js:588:12)
    at Generator.renderFile (path\npm\node_modules\@asyncapi\generator\lib\generator.js:612:17)
    at async Generator.generateFile (path\npm\node_modules\@asyncapi\generator\lib\generator.js:572:27)
    at async Walker.<anonymous> (path\npm\node_modules\@asyncapi\generator\lib\generator.js:440:13)
[cant generate.zip](https://github.com/asyncapi/generator/files/5012959/cant.generate.zip)

```

#### How to Reproduce

- See attached file [cant generate.zip](https://github.com/asyncapi/generator/files/5012964/cant.generate.zip), this is what caused the issue, place it in any template and try generate something. 

#### Expected behavior
Expected it to just copy the file to the new location instead of trying to generate it.

#### Possible solution
Only generate .njk files and just copy all other types.

**Comment by fmvilas** [comment]
There's already a solution for this. Check out `nonRenderableFiles` in the [docs](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file).

**Comment by jonaslagoni** [comment]
Was just about to close it... Found it as well 😅
