### ISSUE TITLE
cannot run commands

### ISSUE THREAD

**Issue by danPudwellUK** [asyncapi/generator#52]
Installed the latest version of asynapi-generator:
npm install -g asyncapi-generator

ran command:
ag test-wss-api.yaml markdown

get error:
/Users/xxx/.nvm/versions/node/v8.0.0/lib/node_modules/asyncapi-generator/lib/generator.js:352
    ...config,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v8.0.0/lib/node_modules/asyncapi-generator/cli.js:7:18)

same error with:
ag -V

**Comment by danPudwellUK** [comment]
I've updated node to 11.13.0 and it works
I think some documentation on compatible node versions would be helpful.

**Comment by fmvilas** [comment]
Isn't version 7.6+ enough for the `...` operator?

**Comment by fmvilas** [comment]
Fixed. The minimum version required is 8.5.
