### ISSUE TITLE
Error: Cannot find: /node_modules/@asyncapi/generator/node_modules/@asyncapi/nodejs-template/node_modules/@asyncapi/generator-filters'

### ISSUE THREAD

**Issue by reselbob** [asyncapi/generator#532]
Help?

I am running some pretty vanilla generation code using the Generator. The [readme here ](https://github.com/reselbob/simpleasyncapi/blob/main/README.md)shows you how to recreate the error in Katacoda

I get this error on build

```
Error: Cannot find module '/root/simpleasyncapi/gen/node_modules/@asyncapi/generator/node_modules/@asyncapi/nodejs-template/node_modules/@asyncapi/generator-filters'
Require stack:
- /root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/filtersRegistry.js
- /root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/generator.js
- /root/simpleasyncapi/gen/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/filtersRegistry.js:80:13
    at Array.map (<anonymous>)
    at registerConfigFilters (/root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/filtersRegistry.js:72:32)
    at module.exports.registerFilters (/root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/filtersRegistry.js:15:9)
    at Generator.generate (/root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/generator.js:181:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/filtersRegistry.js',
    '/root/simpleasyncapi/gen/node_modules/@asyncapi/generator/lib/generator.js',
    '/root/simpleasyncapi/gen/index.js'
  ]
}
```

Here is the code

```
const path = require('path');
const Generator = require('@asyncapi/generator');
const generator = new Generator('@asyncapi/nodejs-template', path.resolve(__dirname, "output"));
generator.templateParams = {server:"mosquitto"};
generator
  .generateFromFile('asyncapi.yaml')
  .then(() => {
    console.log('Done!');
  })
  .catch(console.error);

```

Here is the file system

```
.
├── asyncapi.yaml
├── index.js
├── output
├── package.json
└── package-lock.json
```

Help? I've been struggling with this for an hour or two.

If for some reason this is an error of my own doing, please accept my most embarrassed and sincere apologies in advance.

**Comment by magicmatatjahu** [comment]
@reselbob Hi! Thanks for reporting issues! We have identically issue submitted 2 days ago https://github.com/asyncapi/generator/issues/531 and also PR for fixing it https://github.com/asyncapi/generator/pull/530
Please wait for review/merge. We apologize for inconvenience.

**Comment by reselbob** [comment]
Wow!!!

Thank you for your fast response!
