### ISSUE TITLE
React warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by micaelmbagira** [asyncapi/generator#583]
#### Describe the bug
Using the generator with the markdown template shows React warnings.

```
➜ npx ag https://bit.ly/asyncapi @asyncapi/markdown-template -o example

Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at Server (/test/asyncapi-bug/node_modules/@asyncapi/markdown-template/__transpiled/asyncapi.js:173:3)
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Text>. See https://reactjs.org/link/warning-keys for more information.
    at Schema (/test/asyncapi-bug/node_modules/@asyncapi/markdown-template/__transpiled/asyncapi.js:257:3)


Done! ✨
Check out your shiny new generated files at /test/asyncapi-bug/example.
```
#### How to Reproduce
- `npx ag https://bit.ly/asyncapi @asyncapi/markdown-template -o example`

Or 

- `npm install @asyncapi/markdown-template`
- `npm install @asyncapi/generator`
- `npx ag https://bit.ly/asyncapi @asyncapi/markdown-template -o example`
 
#### Expected behavior
There should not be any error or warning.

**Comment by jonaslagoni** [comment]
Hey @micaelmbagira, thanks for the issue, gonna move this issue to the @asyncapi/markdown-template.

Related to https://github.com/asyncapi/generator-react-sdk/issues/37
