### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by fgadaleta** [asyncapi/generator#893]
Debian package seems to be corrupt.

`npm install` from the cloned repo terminates with errors

```
sudo npm install -g @asyncapi
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@asyncapi": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-21T11_05_40_874Z-debug-0.log
(base) frag@daedalus:~/c0ding/asyncapi/generator$ sudo npm install -g @asyncapi/ag
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@asyncapi%2fag - Not found
npm ERR! 404 
npm ERR! 404  '@asyncapi/ag@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-21T11_05_56_154Z-debug-0.log
(base) frag@daedalus:~/c0ding/asyncapi/generator$ npm install 

up to date, audited 1247 packages in 30s

47 packages are looking for funding
  run `npm fund` for details

20 vulnerabilities (17 moderate, 2 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

```

How to install the generator?

**Comment by derberg** [comment]
Hey, sorry but packages like `@asyncapi` and `@asyncapi/ag` do not exist.

You install generator with `@asyncapi/generator` if you want to use it as library. In case of CLI I think in docs we already suggest to perform installation of the AsyncAPI CLI, so `@asyncapi/cli`

**Comment by fgadaleta** [comment]
even that fails

I install with 
```
sudo npm install -g @asyncapi/cli
[sudo] password for frag: 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@asyncapi/modelina@0.59.9',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@oclif/core@1.22.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml@2.2.0',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 923 packages, and audited 924 packages in 31s

89 packages are looking for funding
  run `npm fund` for details

8 moderate severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

```

and then run 

```
$ asyncapi 
/usr/local/lib/node_modules/@asyncapi/cli/node_modules/@oclif/core/lib/command.js:41
            delete this.globalFlags?.json;
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@asyncapi/cli/node_modules/@oclif/core/lib/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by derberg** [comment]
these are weird 🤔 
do you normally use Node and npm or just for the CLI? maybe just go ahead and try different installation options https://github.com/asyncapi/cli#installation. We provide binaries that do not require node and npm.

**Comment by fgadaleta** [comment]
I tried other methods too. 
Debian package seems corrupt and tar.gz too
Maybe links are broken? 

Can you check?
