### ISSUE TITLE
HTML generator not handling circular references correctly

### ISSUE THREAD

**Issue by synaos-bwi** [asyncapi/generator#939]
#### Describe the bug
A message that contains a payload with a circular reference is not named correctly, but is named <anonymous-message-N>with N being an integer.

VERSION
  @asyncapi/cli/0.30.2 win32-x64 node-v16.13.0

#### How to Reproduce
Call the following CLI command on the attached minimal reproducible example (MRE) and examine the generated html file:
`asyncapi generate fromTemplate ./cycle-mwe.yml @asyncapi/html-template -o test.html --force-write`

```
asyncapi: 2.5.0
info:
  title: storage API
  version: '0.0.1'
channels:
  toy.events:
    subscribe:
      message:
          $ref: '#/components/messages/toyCollectionFilled'
 
components:
  messages:
    toyCollectionFilled:
      payload:
        $ref: '#/components/schemas/ToyCollection'
 
  schemas:
    ToyCollection:
      type: object
      description: generic toys
      properties:
        Matryoshkas:
          type: array
          items:
            $ref: '#/components/schemas/Matryoshka'
        dolls:
          type: array
          items:
            $ref: '#/components/schemas/Doll'
    Matryoshka:
      description: a container for toys
      type: object
      properties:
        id:
          type: string
        content:
          $ref: '#/components/schemas/ToyCollection'
    Doll:
      type: object
      properties:
        name:
          type: string
```

**Note:** If the content property of Matryoshka in the MRE is commented out, the circluar dependency is removed and the message is named correctly.

#### Expected behavior
The message is named correctly as stated in the spec file.

**Comment by magicmatatjahu** [comment]
@synaos-bwi Could you point me where you have problem?

![image](https://user-images.githubusercontent.com/20404945/231750916-bac88e73-53c9-4748-b0b3-db4169185f8c.png)

I see something like that, where is `named with N being an integer` value?

If you don't see that, please upgrade the generator and/or html template to the latest version.

**Comment by synaos-bwi** [comment]
Using the asyncapi-cli seemed to have used a slightly older version of the generator, but even when calling the most recent genereator directly, I still have the same problem:
![image](https://user-images.githubusercontent.com/117291659/231762551-d3479683-dd1d-4354-91fe-cae099930e3e.png)

My versions and commands:
![image](https://user-images.githubusercontent.com/117291659/231766567-67e195a4-31aa-4ddc-9a1c-abcd056e67d6.png)

Adding the `--debug` flag to the generator states:
```
$ ag --debug cycle-mwe.yml @asyncapi/html-template -o output2 --force-write
Unable to resolve template location at undefined. Package is not available locally. Error: Cannot find module '@asyncapi\html-template\package.json'
Require stack:
- C:\Users\<USER>\AppData\Roaming\npm\node_modules\noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at resolveFileName (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\node_modules\resolve-from\index.js:46:47)
    at utils.getTemplateDetails (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\lib\utils.js:206:30)
    at C:\nvm\v16.13.0\node_modules\@asyncapi\generator\lib\generator.js:367:26
    at new Promise (<anonymous>)
    at Generator.installTemplate (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\lib\generator.js:360:12)
    at Generator.generate (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\lib\generator.js:180:73)
    at Generator.generateFromString (C:\nvm\v16.13.0\node_modules\@asyncapi\generator\lib\generator.js:266:17)
    at async C:\nvm\v16.13.0\node_modules\@asyncapi\generator\cli.js:154:9 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\noop.js'
  ]
}
Template installation started because the template cannot be found on disk.
Template @asyncapi/html-template successfully installed in C:\nvm\v16.13.0\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template.
Version of used template is 0.28.3.
File C:\PATH/TO/SPEC\output2\index.html couldn't be found. Error: ENOENT: no such file or directory, stat 'C:\PATH/TO/SPEC\output2\index.html'
File C:\PATH/TO/SPEC\output2\js\asyncapi-ui.min.js couldn't be found. Error: ENOENT: no such file or directory, stat 'C:\PATH/TO/SPEC\output2\js\asyncapi-ui.min.js'
File C:\PATH/TO/SPEC\output2\css\asyncapi.min.css couldn't be found. Error: ENOENT: no such file or directory, stat 'C:\PATH/TO/SPEC\output2\css\asyncapi.min.css'
File C:\PATH/TO/SPEC\output2\css\global.min.css couldn't be found. Error: ENOENT: no such file or directory, stat 'C:\PATH/TO/SPEC\output2\css\global.min.css'
```

**Comment by derberg** [comment]
please try to add `name` or `messageId` to the message under component.

or, try to install [AsyncAPI CLI](https://github.com/asyncapi/cli) and run generator like
```
asyncapi generate fromTemplate cycle-mwe.yml @asyncapi/html-template -o output2 --force-write
```

**Comment by derberg** [comment]
closing as there was no followup
