### ISSUE TITLE
Error: Cannot find module 'ajv/dist/compile/codegen executing through Docker image

### ISSUE THREAD

**Issue by llobetrj** [asyncapi/generator#986]
#### Describe the bug
Since v1.10.0 version, we are getting below error about missing dependency using docker image of the asyncapi/generator
I saw that there is a fix #966  but i can reproduce it using docker image. 
#### How to Reproduce
I'm running the following command:
```
 docker run --rm -i -v /docs/asyncapi:/app -v /docs/asyncapi/build/output:/app/output asyncapi/generator -o /app/output /app/asyncapi.json @asyncapi/html-template --force-write -p pdf=true -p pdfTimeout=0
 
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/ajv-errors/dist/index.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/ajv.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/assertions.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/index.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/ruleset.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/spectral.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/index.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/utils.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/message.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/operation.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/channel.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/asyncapi.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/index.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/index.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/document.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/parser.js
- /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/index.js
- /usr/local/lib/node_modules/@asyncapi/generator/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/ajv-errors/dist/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/ajv-errors/dist/index.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/ajv.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/assertions.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/index.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/ruleset/ruleset.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/spectral.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@stoplight/spectral-core/dist/index.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/utils.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/message.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/operation.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/channel.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/asyncapi.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/v2/index.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/models/index.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/document.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/parser.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/cjs/index.js',
    '/usr/local/lib/node_modules/@asyncapi/generator/cli.js'
  ]
}
```

#### Expected behavior
A successful created document

**Comment by llobetrj** [comment]
We can close this bug, sorry !!!
I had a cached image in my docker repository
